---
- hosts: "ceph"
  gather_facts: yes
  tasks:
    - name: running deploy role
      import_role:
        name: deploy-infrastructure

- hosts: "webserver"
  gather_facts: yes
  tasks:
    - name: running webserver role
      import_role:
        name: deploy-webservers

- hosts: "galera-cluster-nodes"
  gather_facts: yes
  tasks:
    - name: running galera role
      import_role:
        name: mariadb-galera-cluster

- hosts: "loadbalancer"
  gather_facts: yes
  tasks:
    - name: running lb role
      import_role:
        name: deploy-loadbalancer
