# tasks file for deploy-webservers
---

- name: Ceph mount in webservers
  include: mount-storage.yaml

- name: Install wp and requirements in webservers
  include: install-wp.yaml

- name: Install filebeat in webservers
  include: filebeat.yaml
