---
- name: Install ceph-common package
  apt:
    name: ceph-common
    state: present
  tags:
    - install_ceph_common


- name: Create admin.secret file
  copy:
    content: "AQCsX/1kJ5RTLhAA61M0iYoQKbp235Zu+FlHfg=="
    dest: /root/admin.secret
  tags:
    - create_admin_secret_file

- name: Add entry to /etc/fstab for Ceph
  lineinfile:
    path: /etc/fstab
    line: "ceph1,ceph2,ceph3:6789:/ /var/www/html ceph name=admin,secretfile=/root/admin.secret 0 0"
  tags:
    - configure_fstab
- name: Create mount point directory
  file:
    path: /var/www/html
    state: directory
  tags:
    - configure_fstab
- name: Mount Ceph filesystem
  mount:
    path: /var/www/html
    src: ceph1,ceph2,ceph3:6789:/
    fstype: ceph
    opts: "name=admin,secretfile=/root/admin.secret"
    state: mounted
  tags:
    - mount_ceph
